services:
  - type: web
    name: wwu-backend
    runtime: node
    region: oregon
    plan: starter
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
